{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "# coding: utf-8\n",
    "\n",
    "import os\n",
    "import torch\n",
    "\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "\n",
    "from rdkit import Chem\n",
    "from rdkit.Chem import AllChem\n",
    "from rdkit.Chem import Draw\n",
    "import copy\n",
    "\n",
    "from LitCoordAE import LitCoordAE\n",
    "from data_utils import CODDataModule"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "checkpoint_path = \"/home/bb596/pytorch_dl4chem-geometry/logs/default/version_43/checkpoints/epoch=193-step=145305.ckpt\"\n",
    "checkpoint = torch.load(checkpoint_path, map_location='cpu')\n",
    "hparams = checkpoint['hyper_parameters']\n",
    "\n",
    "model = LitCoordAE.load_from_checkpoint(checkpoint_path, hparams=hparams, strict=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_module = CODDataModule(dataset=hparams['dataset'])\n",
    "data_module.setup()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def optimizeWithFF(mol):\n",
    "\n",
    "    opti_mol = copy.deepcopy(mol)\n",
    "    opti_mol = Chem.AddHs(opti_mol, addCoords=True)\n",
    "#     print(len(opti_mol.GetConformers()))\n",
    "    AllChem.MMFFOptimizeMolecule(opti_mol)\n",
    "    opti_mol = Chem.RemoveHs(opti_mol)\n",
    "\n",
    "    return opti_mol\n",
    "\n",
    "def generateETKDGConf(mol) :\n",
    "    \n",
    "    original_mol = copy.deepcopy(mol)\n",
    "    original_mol.RemoveConformer(0)\n",
    "    original_mol = Chem.AddHs(original_mol)\n",
    "    \n",
    "    try : # EmbedMolecule might not find a conformation\n",
    "        AllChem.EmbedMolecule(original_mol)\n",
    "        original_mol = Chem.RemoveHs(original_mol)\n",
    "        opti_mol = copy.deepcopy(original_mol)\n",
    "        AllChem.MMFFOptimizeMolecule(opti_mol)\n",
    "        opti_mol = Chem.RemoveHs(opti_mol)\n",
    "    except :\n",
    "        original_mol = None\n",
    "        opti_mol = None\n",
    "\n",
    "    return original_mol, opti_mol\n",
    "\n",
    "def getRMSD(reference_mol, positions):\n",
    "    \"\"\"\n",
    "    Args :\n",
    "        reference_mol : RDKit.Molecule\n",
    "        positions : Tensor(n_atom, 3)\n",
    "    \"\"\"\n",
    "\n",
    "    n_atom = reference_mol.GetNumAtoms()\n",
    "\n",
    "    test_cf = Chem.rdchem.Conformer(n_atom)\n",
    "    for k in range(n_atom):\n",
    "        test_cf.SetAtomPosition(k, positions[k].tolist())\n",
    "\n",
    "    test_mol = copy.deepcopy(reference_mol)\n",
    "    test_mol.RemoveConformer(0)\n",
    "    test_mol.AddConformer(test_cf)\n",
    "\n",
    "    try :\n",
    "        test_mol_optimized = optimizeWithFF(test_mol)\n",
    "        rmsd_opti = AllChem.AlignMol(reference_mol, test_mol_optimized)\n",
    "    except :\n",
    "        test_mol_optimized = None\n",
    "        rmsd_opti = None\n",
    "        \n",
    "    rmsd_raw = AllChem.AlignMol(reference_mol, test_mol)\n",
    "        \n",
    "    return rmsd_raw, rmsd_opti, test_mol, test_mol_optimized"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_conformations(batch_idx, batch, gen_dir) :\n",
    "    print(batch_idx)\n",
    "    #tensors, mols = batch\n",
    "    #nodes, masks, edges, proximity, pos = tensors\n",
    "        \n",
    "    nodes = batch.nodes\n",
    "    masks = batch.masks\n",
    "    edges = batch.edges\n",
    "    proximity = batch.proximities\n",
    "    pos = batch.positions\n",
    "    mols = batch.mols\n",
    "    \n",
    "    postZ_mu, postZ_lsgms, priorZ_mu, priorZ_lsgms, X_pred, PX_pred = model(nodes, masks, edges, proximity, pos)\n",
    "    \n",
    "    rmsds_raw = []\n",
    "    rmsds_opti = []\n",
    "    for mol_idx, (ref_mol, gen_pos) in enumerate(zip(mols, PX_pred)) :\n",
    "        i = batch_idx * len(mols) + mol_idx\n",
    "#         print(i)\n",
    "        \n",
    "        rmsd_raw, rmsd_opti, test_mol, test_mol_optimized = getRMSD(ref_mol, gen_pos)\n",
    "        rmsds_raw.append(rmsd_raw)\n",
    "        if rmsd_opti is not None :\n",
    "            rmsds_opti.append(rmsd_opti)\n",
    "        w = Chem.SDWriter(f\"{gen_dir}{i}.sdf\")\n",
    "        \n",
    "        etkdg_conf, mmff_conf = generateETKDGConf(ref_mol)\n",
    "        \n",
    "        final_mol = copy.deepcopy(ref_mol)\n",
    "        for mol in [test_mol, test_mol_optimized, etkdg_conf, mmff_conf] :\n",
    "            if mol != None :\n",
    "                final_mol.AddConformer(mol.GetConformer(0), assignId=True)\n",
    "            \n",
    "        Chem.rdMolAlign.AlignMolConformers(final_mol)\n",
    "            \n",
    "        for conf_id in range(len(final_mol.GetConformers())) :\n",
    "            w.write(final_mol, confId=conf_id)\n",
    "        \n",
    "        w.close()\n",
    "        \n",
    "        AllChem.Compute2DCoords(final_mol)\n",
    "        Draw.MolToFile(final_mol, f\"{gen_dir}{i}.png\") \n",
    "\n",
    "    rmsds_raw = np.array(rmsds_raw)\n",
    "    rmsds_opti = np.array(rmsds_opti)\n",
    "#     print(f\"Mean RMSD raw = {rmsds_raw.mean()}\")\n",
    "#     print(f\"Median RMSD raw = {np.median(rmsds_raw)}\")\n",
    "#     print(f\"Mean RMSD opti = {rmsds_opti.mean()}\")\n",
    "#     print(f\"Median RMSD opti = {np.median(rmsds_opti)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "False\n",
      "1\n",
      "False\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3427, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-7-100ff30f09fd>\", line 4, in <module>\n",
      "    generate_conformations(batch_idx, batch, gen_dir)\n",
      "  File \"<ipython-input-6-6fd912066ae2>\", line 41, in generate_conformations\n",
      "    w.close()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2054, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3427, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-7-100ff30f09fd>\", line 4, in <module>\n",
      "    generate_conformations(batch_idx, batch, gen_dir)\n",
      "  File \"<ipython-input-6-6fd912066ae2>\", line 41, in generate_conformations\n",
      "    w.close()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2054, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3347, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2057, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2054, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3427, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-7-100ff30f09fd>\", line 4, in <module>\n",
      "    generate_conformations(batch_idx, batch, gen_dir)\n",
      "  File \"<ipython-input-6-6fd912066ae2>\", line 41, in generate_conformations\n",
      "    w.close()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2054, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3347, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2057, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2054, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2932, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3156, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3366, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2057, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2054, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"/home/bb596/.conda/envs/rdenv/lib/python3.7/genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "gen_dir = 'generation_sdf_qm9/'\n",
    "Path(gen_dir).mkdir(exist_ok=True)\n",
    "for batch_idx, batch in enumerate(data_module.test_dataloader()) :\n",
    "    generate_conformations(batch_idx, batch, gen_dir)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  },
  "toc-autonumbering": false,
  "toc-showcode": false,
  "toc-showmarkdowntxt": false
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
